"""create normalized cloud schema

Revision ID: acf6e5ed93a7
Revises:
Create Date: 2026-07-28 22:16:04.389880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf6e5ed93a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account_type', sa.Enum('SUPER_ADMIN', 'GLOBAL_ADMIN', 'JUDGE', name='account_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('rut_normalized', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'LOCKED', name='user_status', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_type <> 'JUDGE' OR rut_normalized IS NOT NULL", name='ck_judge_requires_rut'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut_normalized'),
    sa.UniqueConstraint('username')
    )
    op.create_index('uq_users_single_fixed_account_type', 'users', ['account_type'], unique=True, postgresql_where=sa.text("account_type IN ('SUPER_ADMIN', 'GLOBAL_ADMIN')"), sqlite_where=sa.text("account_type IN ('SUPER_ADMIN', 'GLOBAL_ADMIN')"))
    op.create_table('auth_recovery_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_recovery_requests_user_id'), 'auth_recovery_requests', ['user_id'], unique=False)
    op.create_table('championships',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/Santiago', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'PENDING_DELETION', 'DELETED', name='championship_status', native_enum=False, create_constraint=True), server_default='DRAFT', nullable=False),
    sa.Column('responsible_admin_id', sa.Uuid(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championships_status'), 'championships', ['status'], unique=False)
    op.create_index('uq_championships_single_active', 'championships', ['status'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('credential_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'DELIVERED', 'REGENERATED', name='credential_event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_events_user_id'), 'credential_events', ['user_id'], unique=False)
    op.create_table('system_roles',
    sa.Column('id', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('super_admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('global_admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_system_roles_single_row'),
    sa.CheckConstraint('super_admin_user_id <> global_admin_user_id', name='ck_system_roles_distinct_users'),
    sa.ForeignKeyConstraint(['global_admin_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['super_admin_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_admin_user_id'),
    sa.UniqueConstraint('super_admin_user_id')
    )
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('championship_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_championship_id'), 'audit_logs', ['championship_id'], unique=False)
    op.create_index('ix_audit_logs_championship_occurred', 'audit_logs', ['championship_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('championship_deletion_confirmations',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_step', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confirmation_step BETWEEN 1 AND 3', name='ck_deletion_confirmation_step'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('championship_id', 'confirmation_step', name='uq_deletion_confirmation_step')
    )
    op.create_index(op.f('ix_championship_deletion_confirmations_championship_id'), 'championship_deletion_confirmations', ['championship_id'], unique=False)
    op.create_table('competition_days',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('competition_date', sa.Date(), nullable=False),
    sa.Column('source_sheet_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('sequence >= 1', name='ck_competition_day_sequence'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('championship_id', 'competition_date', name='uq_competition_days_date'),
    sa.UniqueConstraint('championship_id', 'sequence', name='uq_competition_days_sequence')
    )
    op.create_index(op.f('ix_competition_days_championship_id'), 'competition_days', ['championship_id'], unique=False)
    op.create_table('files',
    sa.Column('championship_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('SOURCE_EXCEL', 'EXCEL_EXPORT', 'PDF_EXPORT', name='file_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('bucket_object', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_object')
    )
    op.create_index(op.f('ix_files_championship_id'), 'files', ['championship_id'], unique=False)
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=False)
    op.create_table('categories',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('competition_day_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('bench', sa.Enum('A', 'B', name='bench', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('session', sa.Enum('AM', 'PM', name='session', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('passing_order', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('passing_order >= 0', name='ck_category_passing_order'),
    sa.CheckConstraint('source_row IS NULL OR source_row >= 1', name='ck_category_source_row'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_day_id'], ['competition_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_day_id', 'bench', 'session', 'passing_order', name='uq_categories_passing_order')
    )
    op.create_index(op.f('ix_categories_championship_id'), 'categories', ['championship_id'], unique=False)
    op.create_index(op.f('ix_categories_competition_day_id'), 'categories', ['competition_day_id'], unique=False)
    op.create_table('import_previews',
    sa.Column('championship_draft_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('detected_data', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['championship_draft_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_previews_championship_draft_id'), 'import_previews', ['championship_draft_id'], unique=False)
    op.create_index(op.f('ix_import_previews_expires_at'), 'import_previews', ['expires_at'], unique=False)
    op.create_table('judge_access_windows',
    sa.Column('judge_user_id', sa.Uuid(), nullable=False),
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('competition_day_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_access_window_duration'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_day_id'], ['competition_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_user_id', 'championship_id', 'competition_day_id', name='uq_judge_access_window_day')
    )
    op.create_index(op.f('ix_judge_access_windows_championship_id'), 'judge_access_windows', ['championship_id'], unique=False)
    op.create_index(op.f('ix_judge_access_windows_judge_user_id'), 'judge_access_windows', ['judge_user_id'], unique=False)
    op.create_table('gymnasts',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('club_name', sa.String(length=180), server_default='', nullable=False),
    sa.Column('passing_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('passing_order >= 0', name='ck_gymnast_passing_order'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gymnasts_category_id'), 'gymnasts', ['category_id'], unique=False)
    op.create_index('uq_gymnasts_active_passing_order', 'gymnasts', ['category_id', 'passing_order'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('judge_assignments',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('judge_user_id', sa.Uuid(), nullable=False),
    sa.Column('competition_day_id', sa.Uuid(), nullable=False),
    sa.Column('bench', sa.Enum('A', 'B', name='assignment_bench', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('session', sa.Enum('AM', 'PM', name='assignment_session', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role', sa.Enum('DA', 'DB', 'A', 'E', 'L', 'P', name='judge_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('effective_from_category_id', sa.Uuid(), nullable=False),
    sa.Column('effective_to_category_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_day_id'], ['competition_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['effective_from_category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['effective_to_category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['judge_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_assignments_championship_id'), 'judge_assignments', ['championship_id'], unique=False)
    op.create_index(op.f('ix_judge_assignments_competition_day_id'), 'judge_assignments', ['competition_day_id'], unique=False)
    op.create_index(op.f('ix_judge_assignments_judge_user_id'), 'judge_assignments', ['judge_user_id'], unique=False)
    op.create_index('ix_judge_assignments_scope', 'judge_assignments', ['championship_id', 'competition_day_id', 'bench', 'session', 'role'], unique=False)
    op.create_index('uq_judge_assignments_open_scope', 'judge_assignments', ['championship_id', 'judge_user_id', 'competition_day_id', 'bench', 'session'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'), sqlite_where=sa.text('superseded_at IS NULL'))
    op.create_table('bench_activations',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('competition_day_id', sa.Uuid(), nullable=False),
    sa.Column('bench', sa.Enum('A', 'B', name='activation_bench', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('gymnast_id', sa.Uuid(), nullable=False),
    sa.Column('activated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_day_id'], ['competition_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bench_activations_championship_id'), 'bench_activations', ['championship_id'], unique=False)
    op.create_index(op.f('ix_bench_activations_gymnast_id'), 'bench_activations', ['gymnast_id'], unique=False)
    op.create_index('uq_bench_activations_open', 'bench_activations', ['championship_id', 'competition_day_id', 'bench'], unique=True, postgresql_where=sa.text('deactivated_at IS NULL'), sqlite_where=sa.text('deactivated_at IS NULL'))
    op.create_table('publication_batches',
    sa.Column('championship_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('UP_TO_GYMNAST', 'FULL_CATEGORY', name='publication_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('up_to_gymnast_id', sa.Uuid(), nullable=True),
    sa.Column('published_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(mode = 'UP_TO_GYMNAST' AND up_to_gymnast_id IS NOT NULL) OR (mode = 'FULL_CATEGORY' AND up_to_gymnast_id IS NULL)", name='ck_publication_batch_target'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['up_to_gymnast_id'], ['gymnasts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_batches_category_id'), 'publication_batches', ['category_id'], unique=False)
    op.create_index(op.f('ix_publication_batches_championship_id'), 'publication_batches', ['championship_id'], unique=False)
    op.create_index(op.f('ix_publication_batches_published_at'), 'publication_batches', ['published_at'], unique=False)
    op.create_table('role_score_resolutions',
    sa.Column('gymnast_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('DA', 'DB', 'A', 'E', 'L', 'P', name='resolution_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('effective_value', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('first_received_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'ADMIN', name='resolution_source', native_enum=False, create_constraint=True), server_default='AUTO', nullable=False),
    sa.Column('has_discrepancy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('discrepancy_revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('acknowledged_revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('values_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('DA', 'DB')", name='ck_resolution_role'),
    sa.CheckConstraint('discrepancy_revision >= acknowledged_revision', name='ck_resolution_revisions'),
    sa.CheckConstraint('effective_value >= 0 AND effective_value <= 20', name='ck_resolution_effective_value_range'),
    sa.CheckConstraint('first_received_value IS NULL OR (first_received_value >= 0 AND first_received_value <= 20)', name='ck_resolution_first_value_range'),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gymnast_id', 'role')
    )
    op.create_table('score_summaries',
    sa.Column('gymnast_id', sa.Uuid(), nullable=False),
    sa.Column('da_score', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('db_score', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('a_score', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('e_score', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), server_default='20.00', nullable=False),
    sa.Column('calculation_status', sa.Enum('PROVISIONAL', 'COMPLETE', name='calculation_status', native_enum=False, create_constraint=True), server_default='PROVISIONAL', nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('a_score BETWEEN -10 AND 10 AND e_score BETWEEN -10 AND 10', name='ck_summary_area_ranges'),
    sa.CheckConstraint('da_score BETWEEN 0 AND 20 AND db_score BETWEEN 0 AND 20', name='ck_summary_difficulty_ranges'),
    sa.CheckConstraint('discount BETWEEN 0 AND 20', name='ck_summary_discount_range'),
    sa.CheckConstraint('total_score BETWEEN 0 AND 60', name='ck_summary_total_range'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gymnast_id')
    )
    op.create_table('published_results',
    sa.Column('publication_batch_id', sa.Uuid(), nullable=False),
    sa.Column('gymnast_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('club_name', sa.String(length=180), nullable=False),
    sa.Column('passing_order', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('e_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('a_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('display_position', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('passing_order >= 0', name='ck_published_passing_order'),
    sa.CheckConstraint('total_score BETWEEN 0 AND 60', name='ck_published_total_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_batch_id'], ['publication_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_batch_id', 'gymnast_id', name='uq_published_results_batch_gymnast')
    )
    op.create_index(op.f('ix_published_results_category_id'), 'published_results', ['category_id'], unique=False)
    op.create_index(op.f('ix_published_results_gymnast_id'), 'published_results', ['gymnast_id'], unique=False)
    op.create_index(op.f('ix_published_results_publication_batch_id'), 'published_results', ['publication_batch_id'], unique=False)
    op.create_index(op.f('ix_published_results_published_at'), 'published_results', ['published_at'], unique=False)
    op.create_table('score_entries',
    sa.Column('gymnast_id', sa.Uuid(), nullable=False),
    sa.Column('judge_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('activation_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('submission_status', sa.Enum('PENDING', 'SUBMITTED', name='submission_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 20', name='ck_score_entry_value_range'),
    sa.ForeignKeyConstraint(['activation_id'], ['bench_activations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_assignment_id'], ['judge_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_modified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gymnast_id', 'judge_assignment_id', name='uq_score_entries_gymnast_assignment')
    )
    op.create_index(op.f('ix_score_entries_gymnast_id'), 'score_entries', ['gymnast_id'], unique=False)
    op.create_index(op.f('ix_score_entries_judge_assignment_id'), 'score_entries', ['judge_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_entries_judge_assignment_id'), table_name='score_entries')
    op.drop_index(op.f('ix_score_entries_gymnast_id'), table_name='score_entries')
    op.drop_table('score_entries')
    op.drop_index(op.f('ix_published_results_published_at'), table_name='published_results')
    op.drop_index(op.f('ix_published_results_publication_batch_id'), table_name='published_results')
    op.drop_index(op.f('ix_published_results_gymnast_id'), table_name='published_results')
    op.drop_index(op.f('ix_published_results_category_id'), table_name='published_results')
    op.drop_table('published_results')
    op.drop_table('score_summaries')
    op.drop_table('role_score_resolutions')
    op.drop_index(op.f('ix_publication_batches_published_at'), table_name='publication_batches')
    op.drop_index(op.f('ix_publication_batches_championship_id'), table_name='publication_batches')
    op.drop_index(op.f('ix_publication_batches_category_id'), table_name='publication_batches')
    op.drop_table('publication_batches')
    op.drop_index('uq_bench_activations_open', table_name='bench_activations', postgresql_where=sa.text('deactivated_at IS NULL'), sqlite_where=sa.text('deactivated_at IS NULL'))
    op.drop_index(op.f('ix_bench_activations_gymnast_id'), table_name='bench_activations')
    op.drop_index(op.f('ix_bench_activations_championship_id'), table_name='bench_activations')
    op.drop_table('bench_activations')
    op.drop_index('ix_judge_assignments_scope', table_name='judge_assignments')
    op.drop_index('uq_judge_assignments_open_scope', table_name='judge_assignments', postgresql_where=sa.text('superseded_at IS NULL'), sqlite_where=sa.text('superseded_at IS NULL'))
    op.drop_index(op.f('ix_judge_assignments_judge_user_id'), table_name='judge_assignments')
    op.drop_index(op.f('ix_judge_assignments_competition_day_id'), table_name='judge_assignments')
    op.drop_index(op.f('ix_judge_assignments_championship_id'), table_name='judge_assignments')
    op.drop_table('judge_assignments')
    op.drop_index('uq_gymnasts_active_passing_order', table_name='gymnasts', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_gymnasts_category_id'), table_name='gymnasts')
    op.drop_table('gymnasts')
    op.drop_index(op.f('ix_judge_access_windows_judge_user_id'), table_name='judge_access_windows')
    op.drop_index(op.f('ix_judge_access_windows_championship_id'), table_name='judge_access_windows')
    op.drop_table('judge_access_windows')
    op.drop_index(op.f('ix_import_previews_expires_at'), table_name='import_previews')
    op.drop_index(op.f('ix_import_previews_championship_draft_id'), table_name='import_previews')
    op.drop_table('import_previews')
    op.drop_index(op.f('ix_categories_competition_day_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_championship_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_index(op.f('ix_files_championship_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_competition_days_championship_id'), table_name='competition_days')
    op.drop_table('competition_days')
    op.drop_index(op.f('ix_championship_deletion_confirmations_championship_id'), table_name='championship_deletion_confirmations')
    op.drop_table('championship_deletion_confirmations')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_championship_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_championship_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('system_roles')
    op.drop_index(op.f('ix_credential_events_user_id'), table_name='credential_events')
    op.drop_table('credential_events')
    op.drop_index('uq_championships_single_active', table_name='championships', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_championships_status'), table_name='championships')
    op.drop_table('championships')
    op.drop_index(op.f('ix_auth_recovery_requests_user_id'), table_name='auth_recovery_requests')
    op.drop_table('auth_recovery_requests')
    op.drop_index('uq_users_single_fixed_account_type', table_name='users', postgresql_where=sa.text("account_type IN ('SUPER_ADMIN', 'GLOBAL_ADMIN')"), sqlite_where=sa.text("account_type IN ('SUPER_ADMIN', 'GLOBAL_ADMIN')"))
    op.drop_table('users')
    # ### end Alembic commands ###
